TASK1:
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: /home/datasets/mix_data/DeVLBert/vqa/
  features_h5path1: /home/datasets/mix_data/DeVLBert/vqa/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb
#  features_h5path1: /home/datasets/mix_data/DeVLBert/coco/coco_test_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 16
  max_region_num: 100
  batch_size: 256
#256
  eval_batch_size: 1024
  train_split: trainval
  val_split: minval
  lr: 0.00004
  num_epoch: 20
TASK5:
  name: VCR_Q-A
  type: VL-logit
  loss: CrossEntropyLoss
  process: expand
  task_id: 6
  dataroot: /home/datasets/mix_data/DeVLBert/vcr
  features_h5path1: /home/datasets/mix_data/DeVLBert/vcr/VCR_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: /home/datasets/mix_data/DeVLBert/vcr/VCR_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: /home/datasets/VCR/train.jsonl
  val_annotations_jsonpath: /home/datasets/VCR/val.jsonl
  max_seq_length: 60
  max_region_num: 100
  batch_size: 16
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK6:
  name: VCR_QA-R
  type: VL-logit
  loss: CrossEntropyLoss
  process: expand
  task_id: 7
  dataroot: /home/datasets/mix_data/DeVLBert/vcr
  features_h5path1: /home/datasets/mix_data/DeVLBert/vcr/VCR_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: /home/datasets/mix_data/DeVLBert/vcr/VCR_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: /home/datasets/VCR/train.jsonl
  val_annotations_jsonpath: /home/datasets/VCR/val.jsonl
  max_seq_length: 80
  max_region_num: 100
  batch_size: 16
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK14:
  name: RetrievalFlickr30k
  type: VL-logit
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 14
#  dataroot: /home/datasets/mix_data/DeVLBert/flickr
  dataroot: /home/datasets/mix_data/vilbert/datasets/flickr30k
  features_h5path1: /home/datasets/mix_data/vilbert/datasets/flickr30k/flickr30k_resnext152_faster_rcnn_genome.lmdb
#  features_h5path1: /home/datasets/mix_data/DeVLBert/flickr/flickr30k_resnet101_faster_rcnn_genome.lmdb
#  features_h5path1: /home/datasets/mix_data/DeVLBert/flickr/flickr30k_test_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: ''
#  train_annotations_jsonpath: /home/datasets/mix_data/vilbert/datasets/flickr30k/all_data_final_train_2014.jsonline
#  val_annotations_jsonpath: /home/datasets/mix_data/vilbert/datasets/flickr30k/all_data_final_val_set0_2014.jsonline
  train_annotations_jsonpath: /home/datasets/mix_data/vilbert/datasets/flickr30k/all_data_final_train_2014.jsonline
  val_annotations_jsonpath: /home/datasets/mix_data/vilbert/datasets/flickr30k/all_data_final_test_set0_2014.jsonline
#  val_annotations_jsonpath: data/flickr30k/all_data_final_test_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 100
  batch_size: 6
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK10:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 11
  dataroot: /home/wbq/Desktop/0323/DeVLBert-master/data/
  features_h5path1: /home/datasets/mix_data/DeVLBert/refcoco+/refcoco+_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: /home/datasets/mix_data/DeVLBert/refcoco+/refcoco+_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 100
  batch_size: 10
  #256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 30
